import { GetServerSideProps } from 'next'; import Head from 'next/head'; import { parseCookies } from 'nookies';
import { Shell } from '@components/OperatorShell/Shell'; import { useFetch } from 'hooks/useFetch';
export const getServerSideProps: GetServerSideProps = async (ctx) => { const { 'user-token': token } = parseCookies(ctx); if (!token) return { redirect: { destination: '/login?expired=true', permanent: false } }; return { props: {} }; };
export default function BillingPage() {
  const { data } = useFetch<any>('/cowork/finance/invoices?perPage=25'); const invoices=data?.data??data?.result??[];
  const kpis=[{l:'Outstanding',v:'$0.00',c:'#F59E0B',i:'receipt_long'},{l:'Overdue',v:'$800.00',c:'#EF4444',i:'warning'},{l:'Collected',v:'$0.00',c:'#10B981',i:'check_circle'},{l:'Pending Payouts',v:'$0.00',c:'#3B82F6',i:'account_balance'}];
  return (<Shell><Head><title>Billing & Payments | Workeaser</title></Head>
    <h1 className="text-[24px] font-bold text-[#2B3450] mb-6">Billing &amp; Payments</h1>
    <div className="grid grid-cols-4 gap-4 mb-6">{kpis.map(k=>(<div key={k.l} className="bg-surface border border-border rounded-lg p-5"><div className="flex items-center gap-2 mb-2"><span className="material-symbols-outlined text-[20px]" style={{color:k.c}}>{k.i}</span><span className="text-[11px] uppercase tracking-wider text-outline font-semibold">{k.l}</span></div><div className="text-[24px] font-bold text-[#2B3450]">{k.v}</div></div>))}</div>
    <div className="flex gap-2 mb-4">{['Invoices','Payments (Mark Paid)','Partner Billing'].map(t=><button key={t} className="px-4 py-2 text-[13px] font-medium border-b-2 border-primary text-primary bg-transparent cursor-pointer">{t}</button>)}</div>
    <div className="flex gap-3 mb-4 items-center"><select className="px-3 py-2 border border-outline-variant rounded-lg text-[13px] outline-none bg-surface"><option>All Statuses</option></select><select className="px-3 py-2 border border-outline-variant rounded-lg text-[13px] outline-none bg-surface"><option>All Periods</option></select><div className="relative flex-1"><span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-[18px] text-outline">search</span><input type="search" placeholder="Search invoices..." className="w-full pl-10 pr-3.5 py-2.5 border border-outline-variant rounded-lg text-[14px] outline-none" /></div><button className="flex items-center gap-1.5 bg-primary text-on-primary px-4 py-2 rounded-lg text-[13px] font-semibold cursor-pointer border-none"><span className="material-symbols-outlined text-[18px]">add</span>Create Invoice</button></div>
    <div className="bg-surface border border-border rounded-lg overflow-hidden"><table className="w-full text-[13px] border-collapse"><thead><tr className="bg-[#2B3450] text-white text-left text-[11px] uppercase"><th className="p-3">ID</th><th className="p-3">Client</th><th className="p-3">Date</th><th className="p-3">Total</th><th className="p-3">Status</th><th className="p-3"></th></tr></thead>
    <tbody>{Array.isArray(invoices)&&invoices.length>0?invoices.map((i:any)=><tr key={i.id} className="border-b border-border"><td className="p-3 font-medium">#{i.id}</td><td className="p-3">{i.user?.clientAccount?.company_name||'—'}</td><td className="p-3">{i.date||'—'}</td><td className="p-3">${((i.total||0)/100).toFixed(2)}</td><td className="p-3"><span className={`px-2 py-0.5 rounded-full text-[11px] font-medium ${i.status==='paid'?'bg-green-100 text-green-800':'bg-amber-100 text-amber-800'}`}>{i.status||'—'}</span></td><td className="p-3"><span className="material-symbols-outlined text-[18px] text-outline cursor-pointer">visibility</span></td></tr>):<tr><td colSpan={6} className="p-6 text-center text-outline">No invoices found.</td></tr>}</tbody></table></div>
  </Shell>);
}
