import { GetServerSideProps } from 'next'; import Head from 'next/head'; import { parseCookies } from 'nookies';
import { Shell } from '@components/OperatorShell/Shell'; import { useFetch } from 'hooks/useFetch'; import Link from 'next/link'; import { useState } from 'react';
export const getServerSideProps: GetServerSideProps = async (ctx) => { const { 'user-token': token } = parseCookies(ctx); if (!token) return { redirect: { destination: '/login?expired=true', permanent: false } }; return { props: {} }; };
export default function ContractsPage() {
  const [filter,setFilter]=useState('All');
  const { data } = useFetch<any>('/cowork/v2/clients?perPage=100'); const clients=(data?.data??data?.result??[]) as any[];
  const contracts=clients.flatMap((c:any)=>(c.serviceContracts||[]).map((sc:any)=>({...sc,client:c})));
  return (<Shell><Head><title>All Contracts | Workeaser</title></Head>
    <div className="flex justify-between items-center mb-6"><h1 className="text-[24px] font-bold text-[#2B3450]">All Contracts</h1>
      <div className="flex gap-2"><Link href="/operator/contracts/new" className="flex items-center gap-1.5 bg-primary text-on-primary px-5 py-2.5 rounded-lg text-[14px] font-semibold no-underline"><span className="material-symbols-outlined text-[18px]">add</span>New Contract</Link></div></div>
    <div className="flex gap-2 mb-4">{[{l:'All',v:'All'},{l:'Signed',v:'ACTIVE'},{l:'Pending Signature',v:'PENDING'}].map(f=>(<button key={f.l} onClick={()=>setFilter(f.v)} className={`px-4 py-2 text-[13px] font-medium rounded-lg cursor-pointer border ${filter===f.v?'bg-primary text-on-primary border-primary':'bg-surface text-on-surface-variant border-border'}`}>{f.l}</button>))}</div>
    <div className="flex gap-3 mb-4 items-center"><div className="relative flex-1"><span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-[18px] text-outline">search</span><input type="search" placeholder="Filter by client..." className="w-full pl-10 pr-3.5 py-2.5 border border-outline-variant rounded-lg text-[14px] outline-none" /></div></div>
    <div className="bg-surface border border-border rounded-lg overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-[13px] border-collapse"><thead><tr className="bg-[#2B3450] text-white text-left text-[11px] uppercase"><th className="p-3">Client</th><th className="p-3">Service</th><th className="p-3">Room</th><th className="p-3">Start Date</th><th className="p-3">End Date</th><th className="p-3">Channel</th><th className="p-3">Status</th><th className="p-3 w-10"></th></tr></thead>
    <tbody>{contracts.map((sc:any)=><tr key={sc.id} className="border-b border-border"><td className="p-3 font-medium"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center text-[11px] font-semibold text-primary">{(sc.client?.contact_first_name||'?')[0]}{(sc.client?.contact_last_name||'?')[0]}</div>{sc.client?.company_name||sc.client?.contact_first_name||'—'}</div></td><td className="p-3">{sc.serviceType?.name||'—'}</td><td className="p-3">{sc.roomsUnit?.display_name||'—'}</td><td className="p-3">{sc.startedAt||'—'}</td><td className="p-3">{sc.endedAt||'—'}</td><td className="p-3"><span className={`px-2 py-0.5 rounded-full text-[11px] font-medium ${sc.billing_channel==='DIRECT'?'bg-blue-100 text-blue-800':'bg-amber-100 text-amber-800'}`}>{sc.billing_channel}</span></td><td className="p-3"><span className={`px-2 py-0.5 rounded-full text-[11px] font-medium ${sc.status==='ACTIVE'?'bg-green-100 text-green-800':'bg-amber-100 text-amber-800'}`}>{sc.status}</span></td><td className="p-3"><span className="material-symbols-outlined text-[18px] text-outline cursor-pointer">visibility</span> <span className="material-symbols-outlined text-[18px] text-outline cursor-pointer ml-1">open_in_new</span></td></tr>)}</tbody></table></div>
    {contracts.length===0 && <p className="text-outline text-center py-10">No contracts found.</p>}</div>
  </Shell>);
}
