# This is a basic workflow to help you get started with Actions

name: Node.js CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  # This workflow contains a single job called "build"
  deploy:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.SSH_HOST  }}
            USER_NAME : ${{ secrets.SSH_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            DIR="/home/ec2-user/admin-management-api"
            pm2 delete all
            cd $DIR
            
            git checkout main &&
            git pull origin main &&
            npm i &&
            npm run build &&
            cp .env ./build/.env &&
            cd build &&
            npm ci --production &&
            node ace migration:run &&
            pm2 start server.js -s admin-management-api
          '