import { GetServerSideProps } from 'next'; import Head from 'next/head'; import { parseCookies } from 'nookies';
import { Shell } from '@components/OperatorShell/Shell'; import { useFetch } from 'hooks/useFetch'; import { api } from '@services/api'; import { useState } from 'react'; import { toast } from 'react-toastify';
export const getServerSideProps: GetServerSideProps = async (ctx) => { const { 'user-token': token } = parseCookies(ctx); if (!token) return { redirect: { destination: '/login?expired=true', permanent: false } }; return { props: {} }; };
export default function UsersPage() {
  const { data, mutate } = useFetch<any>('/cowork/v2/setup/users'); const [addOpen,setAddOpen]=useState(false); const [form,setForm]=useState<any>({role:'COWORKING'});
  const users:any[]=Array.isArray(data)?data:[];
  const save=async()=>{try{await api.post('/cowork/v2/setup/users',form);setAddOpen(false);mutate();toast.success('User created')}catch{toast.error('Failed')}};
  const iS="px-3 py-2 border border-outline-variant rounded-md text-[13px] outline-none w-full";
  return (<Shell><Head><title>Users & Roles | Workeaser</title></Head>
    <div className="flex justify-between items-center mb-6"><h1 className="text-[24px] font-bold text-[#2B3450]">Users &amp; Roles</h1><button onClick={()=>setAddOpen(true)} className="flex items-center gap-1.5 bg-primary text-on-primary px-4 py-2 rounded-lg text-[14px] font-semibold cursor-pointer border-none"><span className="material-symbols-outlined text-[18px]">add</span>Add User</button></div>
    {addOpen && <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center" onClick={()=>setAddOpen(false)}><div className="bg-surface rounded-xl shadow-2xl max-w-lg w-full mx-4 p-6" onClick={e=>e.stopPropagation()}><h2 className="text-[18px] font-semibold text-[#2B3450] mb-4">Add User</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4"><input placeholder="First Name *" value={form.first_name||''} onChange={e=>setForm({...form,first_name:e.target.value})} className={iS} /><input placeholder="Last Name *" value={form.last_name||''} onChange={e=>setForm({...form,last_name:e.target.value})} className={iS} /><input placeholder="Email *" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})} className={iS} /><input placeholder="Phone" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})} className={iS} /><input placeholder="Address" value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})} className={iS} /><select value={form.role||'COWORKING'} onChange={e=>setForm({...form,role:e.target.value})} className={iS}><option value="ADMIN">Administrator</option><option value="COWORKING">Assistant</option><option value="CLIENT">Customer</option></select></div>
      <textarea placeholder="Notes" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})} className={`${iS} mb-4 min-h-[60px]`} />
      <div className="flex gap-3"><button onClick={save} className="bg-primary text-on-primary px-4 py-2 rounded-md text-[13px] font-semibold cursor-pointer border-none">Create</button><button onClick={()=>setAddOpen(false)} className="bg-surface border border-border px-4 py-2 rounded-md text-[13px] cursor-pointer">Cancel</button></div>
    </div></div>}
    <div className="bg-surface border border-border rounded-lg overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-[13px] border-collapse"><thead><tr className="bg-[#2B3450] text-white text-left text-[11px] uppercase"><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Role</th><th className="p-3">Phone</th><th className="p-3">Modules</th></tr></thead>
    <tbody>{users.map((u:any)=><tr key={u.id} className="border-b border-border"><td className="p-3 font-medium">{u.first_name} {u.last_name}</td><td className="p-3">{u.email}</td><td className="p-3"><span className={`px-2 py-0.5 rounded-full text-[11px] font-medium ${u.role==='ADMIN'?'bg-blue-100 text-blue-800':'bg-green-100 text-green-800'}`}>{u.role}</span></td><td className="p-3">{u.phone||'—'}</td><td className="p-3">{(u.modules||[]).join(', ')||'—'}</td></tr>)}</tbody></table></div>
  </Shell>);
}
